# Generated by Django 4.1.6 on 2023-02-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.CharField(max_length=600, verbose_name='Description')),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('clubid', models.CharField(max_length=100, verbose_name='clubid')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='hub.club')),
            ],
        ),
    ]
