# Generated by Django 4.1.6 on 2023-02-04 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=600, verbose_name='Description')),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('clubid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='clubid')),
                ('featured', models.BooleanField(default=False)),
                ('iamgeURL', models.CharField(max_length=300)),
                ('memberCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('memberCount', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='hub.club')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('school', models.CharField(default='uci', max_length=100)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('following_clubs', models.ManyToManyField(blank=True, related_name='user_clubs', to='hub.club')),
                ('following_events', models.ManyToManyField(blank=True, related_name='user_events', to='hub.event')),
                ('following_tags', models.ManyToManyField(blank=True, related_name='user_tags', to='hub.tag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='event_tags', to='hub.tag'),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='club_tags', to='hub.tag'),
        ),
    ]
