# Generated by Django 4.1.6 on 2023-02-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='iamgeURL',
            new_name='imageURL',
        ),
        migrations.RemoveField(
            model_name='club',
            name='featured',
        ),
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clubs_owned',
            field=models.ManyToManyField(blank=True, related_name='owned_clubs', to='hub.club'),
        ),
    ]
