# Generated by Django 4.1.6 on 2023-02-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_club_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='iamgeURL',
            field=models.CharField(default='blank.txt', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='clubid',
            field=models.CharField(max_length=100, unique=True, verbose_name='clubid'),
        ),
    ]
