# Generated by Django 4.1.6 on 2023-02-04 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0003_club_iamgeurl_alter_club_clubid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('following_clubs', models.ManyToManyField(blank=True, related_name='user_clubs', to='hub.club')),
                ('following_events', models.ManyToManyField(blank=True, related_name='user_events', to='hub.event')),
                ('following_tags', models.ManyToManyField(blank=True, related_name='user_tags', to='hub.tag')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='club_tags', to='hub.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='event_tags', to='hub.tag'),
        ),
    ]
